# Generated by Django 5.2.7 on 2026-02-09 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('student_class', models.CharField(max_length=50)),
                ('board', models.CharField(max_length=100)),
                ('course_type', models.CharField(choices=[('JEE', 'JEE Main & Advanced | WBJEE'), ('NEET', 'NEET'), ('FOUNDATION', 'Foundation'), ('BOARDS', 'Boards')], max_length=50)),
                ('centre', models.CharField(max_length=255)),
                ('page_source', models.CharField(help_text='Which landing page: JEE or NEET', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_contacted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Landing Page Registration',
                'verbose_name_plural': 'Landing Page Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
