# Generated by Django 5.2.7 on 2026-02-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpageregistration',
            name='course_type',
            field=models.CharField(choices=[('JEE', 'JEE Main & Advanced | WBJEE'), ('NEET', 'NEET'), ('FOUNDATION', 'Foundation'), ('BOARDS', 'Boards'), ('CRP', 'CRP (Classroom Program)'), ('NCRP', 'NCRP (Non-Classroom Program)')], max_length=50),
        ),
    ]
