# Generated by Django 5.2.7 on 2026-02-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_registrations', '0002_alter_landingpageregistration_course_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingPageRegistration',
        ),
    ]
