# Generated by Django 5.2.7 on 2025-11-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
    ]
