name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Pathfinder_new_website
            git pull origin main
            
            # Backend
            cd backend
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart gunicorn
            
            # Frontend
            cd ../frontend
            npm install
            npm run build
            
            # Copy built files to Nginx web root
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/
            
            sudo systemctl restart nginx
